import "styles/globals.css";

import { Footer } from "components/layout/footer";
import Header from "components/layout/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "store/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutProps = {
	children: React.ReactNode
}


export default async function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en">
		<body className={inter.className + " overflow-x-hidden"}>
		<Providers>
			<Header/>
			{children}
			<Footer/>
		</Providers>
		</body>
		</html>
	);
}